CREATE DATABASE account_db;

\connect customer_db

GRANT ALL PRIVILEGES ON DATABASE customer_db TO banking;
GRANT ALL PRIVILEGES ON SCHEMA public TO banking;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO banking;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO banking;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO banking;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON SEQUENCES TO banking;

\connect account_db

GRANT ALL PRIVILEGES ON DATABASE account_db TO banking;
GRANT ALL PRIVILEGES ON SCHEMA public TO banking;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO banking;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO banking;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO banking;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON SEQUENCES TO banking;





